### ISSUE TITLE
SMS authentication error - TypeError: Cannot read property 'sigBytes' of undefined

### ISSUE THREAD

**Issue by songhwee1** [songhwee1/Danim#15]
인증번호 전송 버튼을 누르면 전송이 완료되었다는 팝업은 뜨지만 다음과 같은 에러가 발생하고, 문자전송도 되지 않습니다.
`
TypeError: Cannot read property 'sigBytes' of undefined
    at Object.init (C:\Danim\Danim_FE\node_modules\crypto-js\hmac.js:53:22)
    at Object.subtype.init (C:\Danim\Danim_FE\node_modules\crypto-js\core.js:149:46)
    at Object.create (C:\Danim\Danim_FE\node_modules\crypto-js\core.js:176:32)
    at C:\Danim\Danim_FE\server\routes\index.js:81:35
    at Layer.handle [as handle_request] (C:\Danim\Danim_FE\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Danim\Danim_FE\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Danim\Danim_FE\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Danim\Danim_FE\node_modules\express\lib\router\layer.js:95:5)
    at C:\Danim\Danim_FE\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Danim\Danim_FE\node_modules\express\lib\router\index.js:335:12)
`

**Comment by charmingjae** [comment]
SMS 전송 시 과금 발생으로 현재 기능 비활성화 상태입니다.
회원가입 시 Raw query를 사용하시길 바랍니다.
